# Generated by Django 5.2.11 on 2026-02-25 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Logged')),
                ('grade', models.CharField(choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('EX', 'Excellent'), ('G', 'Good'), ('P', 'Poor')], default='M', max_length=2, verbose_name='Condition:')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='main_app.card')),
            ],
        ),
    ]
