# Generated by Django 5.2.11 on 2026-02-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
